baseURL: "https://juamsv.netlify.app/"
title: Juam Blog
paginate: 5
theme: "hugo-PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Juam Blog
  description: "Juam Blog"
  keywords: [Blog, Portfolio, DevOps]
  author: Juam Sousa
  # author: ["Me", "You"] # multiple authors
  images: ["avatar.svg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  ShareButtons: ["linkedin", "telegram"] # To customize which share buttons to be enabled on page

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: DevOps and SRE
    subtitle: "Welcome to my Blog"
    imageUrl: "avatar.svg"
    imageWidth: 240
    imageHeight: 240
    # imageWidth: 120
    # imageHeight: 120
    imageTitle: Meu Avatar
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      - name: Portifolio
        url: portifolio

  # home-info mode
  homeInfoParams:
    Title: "Ola, eu sou o Juam \U0001F44B"
    Content: Bem vindo ao meu blog

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/juam-sv"
    - name: github
      url: "https://github.com/juam-sv/"
    - name: telegram
      url: "https://t.me/juam_sv"
    - name: email
      url: mailto:juam13pb@gmail.com
    
  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/juam-sv/hugo/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: portifolio
      name: Portifolio
      url: /portifolio/
      weight: 20
    - identifier: About
      name: About
      url: /posts/sobre
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    - identifier: Resume
      name: Resume
      url: https://rxresu.me/juamsv/curriculo
      weight: 50
    - identifier: Linktree
      name: Linktree
      url: https://linktr.ee/juam.sv
      weight: 60
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai